services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "60080:80"
    volumes:
      - /etc/mosdns:/etc/mosdns