log:
  level: debug
  production: false
  file: /etc/mosdns/mosdns.log

api:
  http: :8080

plugins:
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 65536
      lazy_cache_ttl: 172800
      dump_file: /etc/mosdns/lazy_cache.dump
      dump_interval: 1024

  - tag: forward_default
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: udp://192.168.32.1

  - tag: reverse_lookup
    type: reverse_lookup
    args:
      size: 65535 # 内置缓存大小。默认 65535。

      # 缓存时间。秒。默认 7200 (2h)。应答记录的 TTL 也会被自动修改，限制在该值以下。
      ttl: 7200
      # 是否主动处理/响应 PTR 请求。如果 PTR 的 IP 命中缓存，则生成应答。
      # 用途举例: 使用网络监视类工具查看网络连接时，开启域名反查功能大概率会看到 IP 对应的
      # 真实域名(如果程序先请求域名再建立连接，而且域名经过了该插件处理。)
      handle_ptr: true

  - tag: main_sequence
    type: sequence
    args:
      - exec: $reverse_lookup
      - matches: has_resp
        exec: accept

      - exec: $lazy_cache
      - matches: has_resp
        exec: accept

      - exec: $forward_default

  # 服务器插件
  - tag: http_server
    type: http_server
    args:
      entries:
        - path: /dns-query
          exec: main_sequence
      src_ip_header: "X-Forwarded-For"
      listen: :80
      cert:
      key:
      idle_timeout: 10 # 空连接超时。单位秒。默认 30。
